"""Investigation Workflow — Final report generation."""
from __future__ import annotations
import json
from utils.llm_router import LLMRouter, TaskType


class InvestigationWorkflow:
    def __init__(self, llm_router: LLMRouter):
        self.llm = llm_router

    async def generate_report(
        self, investigation_id: str, url: str, debate: dict, recon: list[dict]
    ) -> dict:
        system = """You are AEGIS Chief Report Officer. Generate a comprehensive strategic intelligence
report from multi-agent analysis. Be precise, evidence-based, and actionable. Return ONLY valid JSON."""

        context = json.dumps({
            "debate_synthesis": {k: v for k, v in debate.items()
                                 if k not in ["bull_thesis", "bear_thesis"]},
            "recon_summary": [
                {"agent": r.get("agent_type"), "key_findings": str(r.get("data", {}))[:500]}
                for r in recon if r.get("status") == "completed"
            ][:7],
        })

        prompt = f"""Generate a complete AEGIS strategic intelligence report.
Investigation ID: {investigation_id}
Target URL: {url}

Analysis Context:
{context[:6000]}

Return JSON (all fields required):
{{
  "company_name": "...",
  "confidence_score": <0.0-1.0>,
  "vitality_score": <0-100>,
  "moat_score": <0-100>,
  "risk_score": <0-100>,
  "executive_summary": "<comprehensive 4-5 sentence summary>",
  "bull_thesis": "<bull case paragraph>",
  "bear_thesis": "<bear case paragraph>",
  "skeptic_analysis": "<skeptic audit summary>",
  "final_verdict": "strong_buy|buy|hold|watch|avoid",
  "red_flag_matrix": [
    {{"flag": "...", "severity": "low|medium|high|critical", "category": "..."}}
  ],
  "moat_analysis": {{
    "primary_moat": "...", "strength": "wide|narrow|none", "durability_years": <n>
  }},
  "scenarios": {{
    "bull": {{"probability": 0.3, "outcome": "...", "price_target": "..."}},
    "base": {{"probability": 0.5, "outcome": "...", "price_target": "..."}},
    "bear": {{"probability": 0.2, "outcome": "...", "price_target": "..."}}
  }},
  "recommendations": [
    {{"action": "...", "rationale": "...", "priority": "immediate|short_term|long_term"}}
  ],
  "comparable_companies": ["Company A", "Company B"],
  "next_monitoring_triggers": ["..."],
  "raw_markdown": "<full markdown report with all sections>"
}}"""

        resp = await self.llm.complete(TaskType.REPORT, system, prompt, 3000, 0.4, "json")

        import re
        text = resp.content
        try:
            data = json.loads(text)
        except Exception:
            match = re.search(r'\{[\s\S]*\}', text)
            data = json.loads(match.group()) if match else {}

        # Merge debate synthesis fields if missing
        for key in ["company_name", "confidence_score", "vitality_score", "moat_score", "risk_score"]:
            if key not in data and key in debate:
                data[key] = debate[key]

        # Generate markdown if missing
        if not data.get("raw_markdown"):
            data["raw_markdown"] = self._to_markdown(data, url)

        return data

    def _to_markdown(self, report: dict, url: str) -> str:
        return f"""# AEGIS Strategic Intelligence Report
**Target:** {url}
**Company:** {report.get('company_name', 'Unknown')}
**Verdict:** {report.get('final_verdict', 'N/A').upper()}

---

## Executive Summary
{report.get('executive_summary', '')}

## Bull Case
{report.get('bull_thesis', '')}

## Bear Case
{report.get('bear_thesis', '')}

## Skeptic Audit
{report.get('skeptic_analysis', '')}

## Risk Matrix
{chr(10).join(f"- **{r['flag']}** ({r['severity'].upper()}): {r['category']}" for r in report.get('red_flag_matrix', []))}

## Moat Analysis
{json.dumps(report.get('moat_analysis', {}), indent=2)}

## Scenario Analysis
{json.dumps(report.get('scenarios', {}), indent=2)}

## Recommendations
{chr(10).join(f"- [{r['priority'].upper()}] {r['action']}: {r['rationale']}" for r in report.get('recommendations', []))}

---
*Generated by AEGIS v1.0 — Autonomous Multi-Agent Strategic Intelligence*
"""
